name: Generate SBOM on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened] # Se ejecuta al abrir, actualizar o reabrir el PR
    branches:
      - main # O la rama base que utilices (ej. master, develop)
      - dev

jobs:
  sbom-generation-and-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar el entorno de Java (requerido para Gradle)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # Automatiza la caché de dependencias para que sea más rápido

      # 3. Otorgar permisos de ejecución al script de Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Ejecutar la tarea de CycloneDX para generar el SBOM
      - name: Generate CycloneDX SBOM
        run: ./gradlew cyclonedxBom

      - name: Validate SBOM JSON syntax
        run: |
          cat ./build/reports/cyclonedx/bom.json | python3 -m json.tool > /dev/null
          echo "SBOM JSON is valid"

      # 5. Instalar Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # 6. Ejecutar Trivy directamente sobre el SBOM generado
      - name: Scan SBOM with Trivy
        run: |
          trivy sbom ./build/reports/cyclonedx/bom.json \
            --format table \
            --exit-code 1 \
            --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL

      # 5. Archivar y documentar el SBOM generado como artefacto del PR
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bom-test
          # Por defecto, el plugin genera los archivos en build/reports/
          path: "build/reports/cyclonedx/bom.json"
          if-no-files-found: error # Esto hará que el pipeline falle si no encuentra el archivo, avisándote de inmediato
          retention-days: 14 # Tiempo que se guardará el archivo en GitHub