name: Generate SBOM on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened] # Se ejecuta al abrir, actualizar o reabrir el PR
    branches:
      - main
      - dev

jobs:
  sbom-generation-and-scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Generar el SBOM multimódulo usando Trivy (CycloneDX format)
      - name: Generate Multi-Module SBOM with Trivy
        uses: aquasecurity/trivy-action@0.20.0 # Versión fija de la acción de GitHub para el QMS
        with:
          trivy-version: '0.51.1'              # Motor de Trivy controlado para consistencia
          scan-type: 'repo'                    # Escanea el repositorio de golpe
          scan-ref: '.'                        # Raíz del proyecto (recorrerá Antshrike, mobile, common, wear)
          format: 'cyclonedx'                  # Estándar de la industria médica requerido
          output: 'build/reports/cyclonedx/bom.json' # Ruta de salida esperada para mantener compatibilidad

      # 3. Validar la sintaxis del JSON generado por Trivy
      - name: Validate SBOM JSON syntax
        run: |
          cat ./build/reports/cyclonedx/bom.json | python3 -m json.tool > /dev/null
          echo "SBOM JSON is valid"

      # 4. Escanear el SBOM generado en busca de vulnerabilidades conocidas (SOUP Audit)
      - name: Run Trivy Vulnerability Scan on SBOM
        uses: aquasecurity/trivy-action@0.20.0
        with:
          trivy-version: '0.51.1'
          scan-type: 'sbom'
          scan-ref: 'build/reports/cyclonedx/bom.json' # Apunta al archivo que acabamos de crear en el paso 2
          scanners: 'vuln'                              # Filtramos estrictamente para SOUP (solo vulnerabilidades conocidas)
          format: 'table'
          severity: 'HIGH,CRITICAL'                     # Enfoque en los riesgos de mayor impacto bajo IEC 62304
          exit-code: '0'                                # Mantenemos 0 temporalmente para validación inicial del pipeline

      # 5. Archivar y documentar el SBOM generado como artefacto del PR
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bom-test
          path: "build/reports/cyclonedx/bom.json"
          if-no-files-found: error
          retention-days: 14 # Tiempo que se guardará el archivo en GitHub